spring.application.name=ecommerce-api-web13
server.port=13000

#Database or Datasource config
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=sb13user
spring.datasource.password=yourpassword
spring.datasource.url=jdbc:postgresql://localhost:1300/sb13_db


#JPA configurations
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
