spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:1301/realms/ecommerce

#spring.security.user.name=visal
#spring.security.user.password=123456
#spring.security.user.roles=CUSTOMER

spring.application.name=ecommerce-api-web13
server.port=13000

#Database or Datasource config
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=sb13user
spring.datasource.password=mypassword
spring.datasource.url=jdbc:postgresql://localhost:1300/postgres


#JPA configurations
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB
media.location=D:\\sb-13-media-upload\\
media.client-path=/media
media.base-uri=http://localhost:13000